"""empty message

Revision ID: 44954e52b674
Revises: 
Create Date: 2022-10-31 09:42:47.912242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44954e52b674'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=50), nullable=True),
    sa.Column('precio', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unidades', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('precio', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unidades', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('tamanio', sa.String(length=50), nullable=True),
    sa.Column('precio', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unidades', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('precio', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unidades', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teclado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('precio', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unidades', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teclado')
    op.drop_table('mouse')
    op.drop_table('monitor')
    op.drop_table('laptop')
    op.drop_table('accesorio')
    # ### end Alembic commands ###
